DROP database IF EXISTS pc_xuta;
CREATE DATABASE IF NOT EXISTS `pc_xuta`;

use pc_xuta;

CREATE TABLE IF NOT EXISTS `CUSTOMER` (
  `CUSTOMER_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `CUSTOMER_FIRST_NAME` VARCHAR(50) NOT NULL,
  `CUSTOMER_LAST_NAME` VARCHAR(50),
  `CUSTOMER_GENDER` VARCHAR(10) NOT NULL,
  `CUSTOMER_EMAIL` VARCHAR(50) NOT NULL,
  `CUSTOMER_ADRESS` VARCHAR(50) NOT NULL,
  `CUSTOMER_ALIAS` VARCHAR(15) NOT NULL,
  `CUSTOMER_RATING` VARCHAR(40),
  `CUSTOMER_AGE` INTEGER,  
  PRIMARY KEY (`CUSTOMER_ID`)
) ;

CREATE TABLE IF NOT EXISTS `SUPPLIER` (
  `SUPPLIER_ID` INTEGER NOT NULL AUTO_INCREMENT ,
  `SUPPLIER_NAME` varchar(30) NOT NULL,
  `SUPPLIER_ADRESS` varchar(25) NOT NULL,
  PRIMARY KEY (`SUPPLIER_ID`)
) ;


CREATE TABLE IF NOT EXISTS `PRODUCT` (
  `PRODUCT_ID` INTEGER NOT NULL AUTO_INCREMENT,
  `PRODUCT_NAME` varchar(60) NOT NULL,
  `PRODUCT_TYPE` varchar(30) NOT NULL,
  `PRODUCT_PRICE` float (5,2) NOT NULL DEFAULT 0.00,
  `PRODUCT_STOCK` INTEGER NOT NULL,
  `PRODUCT_RATING` INTEGER NOT NULL DEFAULT 0,
  `SUPPLIER_ID` INTEGER NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`)
);



CREATE TABLE IF NOT EXISTS `INVOICE` (
    `INVOICE_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CUSTOMER_ID` INTEGER NOT NULL,
    `PAYMENT_AMOUNT` float NOT NULL default 0.00,
	`INVOICE_DATE` date NOT NULL,
    `PAYMENT_METHOD` VARCHAR(30) NOT NULL,
    PRIMARY KEY (`INVOICE_ID`)
);

CREATE TABLE IF NOT EXISTS `INVOICE_DETAIL` (
    `INVOICE_ID` INTEGER NOT NULL,
    `PRODUCT_ID` INTEGER NOT NULL,
    `PRODUCT_QUANTITY` INTEGER NOT NULL,
    PRIMARY KEY (`INVOICE_ID`,`PRODUCT_ID`)
);



CREATE TABLE IF NOT EXISTS `SHIPMENT` ( 
  `SHIPMENT_ID` INTEGER NOT NULL  AUTO_INCREMENT,
  `SHIPMENT_PRICE` INTEGER NOT NULL, 
  `SHIPMENT_BRAND` varchar(30) NOT NULL,
  `SHIPMENT_TYPE` varchar(30) NOT NULL,
  `SHIPMENT_REGION` varchar(30) NOT NULL,
  PRIMARY KEY (`SHIPMENT_ID`) 
  );
  
  CREATE TABLE IF NOT EXISTS `INVOICE_SHIPMENT` (
  `INVOICE_ID` INTEGER NOT NULL,
  `SHIPMENT_ID` INTEGER NOT NULL,
  `SHIPMENT_STATUS` varchar(30) NOT NULL,
  `SHIPMENT_DATE` date NOT NULL,
  PRIMARY KEY (`INVOICE_ID`,`SHIPMENT_ID`) 
  );
  



  

  
  
  
  
  