use pc_xuta;

ALTER TABLE `PRODUCT`
ADD CONSTRAINT `fk_Product_1`
  FOREIGN KEY (`SUPPLIER_ID`)
  REFERENCES `SUPPLIER` (`SUPPLIER_ID`)
  ON DELETE RESTRICT
  ON UPDATE CASCADE;
  
  
ALTER TABLE `INVOICE`
ADD CONSTRAINT `fk_Invoice_1`
  FOREIGN KEY (`CUSTOMER_ID`)
  REFERENCES `CUSTOMER` (`CUSTOMER_ID`)
  ON DELETE RESTRICT
  ON UPDATE CASCADE; 
  
ALTER TABLE `INVOICE_DETAIL`
ADD CONSTRAINT `fk_InvDetail_1`
  FOREIGN KEY (`INVOICE_ID`)
  REFERENCES `INVOICE` (`INVOICE_ID`)
  ON DELETE RESTRICT
  ON UPDATE CASCADE; 
  
ALTER TABLE `INVOICE_DETAIL`
ADD CONSTRAINT `fk_InvDetail_2`
  FOREIGN KEY (`PRODUCT_ID`)
  REFERENCES `PRODUCT` (`PRODUCT_ID`)
  ON DELETE RESTRICT
  ON UPDATE CASCADE;
  

ALTER TABLE `INVOICE_SHIPMENT`
ADD CONSTRAINT `fk_InvShip_1`
  FOREIGN KEY (`INVOICE_ID`)
  REFERENCES  `INVOICE` (`INVOICE_ID`)
  ON DELETE RESTRICT
  ON UPDATE CASCADE;

ALTER TABLE `INVOICE_SHIPMENT`
ADD CONSTRAINT `fk_InvShip_2`
  FOREIGN KEY (`SHIPMENT_ID`)
  REFERENCES  `SHIPMENT` (`SHIPMENT_ID`)
  ON DELETE RESTRICT
  ON UPDATE CASCADE;

  


